### ISSUE TITLE
Dto classes to records

### ISSUE THREAD

**Issue by alxmcs** [JirenMTA/dotnet-2023#2]
В серверном проекте необходимо переделать имеющиеся классы в [рекорды](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/record). Небольшой пример ниже.

Было:
```cs
/// <summary>
///  Dto class for something
/// </summary>
public class SomeDto
{
    /// <summary>
    /// Property for something
    /// </summary>
    public int SomeFieldInt { get; set; }

    /// <summary>
    /// Property for something else
    /// </summary>
    public string SomeFieldStr { get; set; }
}
```

Стало:
```cs
/// <summary>
/// Dto class for something
/// </summary>
/// <param name="SomeFieldInt">Property for something</param>
/// <param name="SomeFieldStr">Property for something else</param>
public record SomeDto(int SomeFieldInt, string SomeFieldStr);
```

Чем это полезно:
* Код стал заметно компактнее,
* Рекорды иммутабельны, что очень удобно для Dto, которые как раз таки изменяться при передаче не должны,
* Объекты имеют позиционный конструктор, так что не получится забыть о каком-либо проперти объекта, как при создании через expression body.

**Comment by JirenMTA** [comment]
@alxmcs  Я решил эту задачу в branch 2-dto-classes-to-record, проверьте, пожалуйста

**Comment by alxmcs** [comment]
Хорошо, открывай pr из `2-dto-classes-to-records` в `main` своего репозитория
