### ISSUE TITLE
 CI/CD

### ISSUE THREAD

**Issue by alxmcs** [JirenMTA/dotnet-2023#5]
Необходимо добавить в проект workflow, который бы запускал юнит тесты при открытии пул-риквеста в main ветку или при непосредственном пуше в main ветку.

О github workflow и том, как их его настроить можно почитать [тут](https://docs.github.com/en/actions/using-workflows/about-workflows).

Пример yaml-файла с вокрфлоу, который практически полностью подходит под эту задачу, можно посмотреть [тут](https://github.com/alxmcs/GIiIBDepartmentBot/blob/main/.github/workflows/SharpDepartmentBot.yml).

>Для этого задания будет проще не заводить отдельную ветку, а сразу пушить в main.

**Comment by JirenMTA** [comment]
@alxmcs Я тоже добавил ```./github/workflow```, проверьте, пожалуйста
